Event listener added to form
linhapeter/1th_js_task_vention pull request #4
Opened 2023-09-20 10:21 UTC by linhapeter

2023-09-20 18:12 UTC, igorTT requested changes
Check IDE configuration. It should be maximum 1 empty line between code lines.
Missed semicolon. IDE should be configured to add missing symbols on save.

2023-09-20 18:12 UTC, igorTT commented on form.js
> +submitButton.setE
What is this?

2023-09-20 18:12 UTC, igorTT commented on form.js
> +    const passwordInput = existingForm.querySelector('input[name="password"]');
You have have access to thess elements because you've just created them. Use emailInput and password from the upper score.
The same for form element.

2023-09-25 13:23 UTC, linhapeter commented
I've merged main into this branch to resolve issues.

2023-09-25 19:30 UTC, igorTT requested changes
Checkout from bugfix/3 meant that. You need to create a separate branch from bugfix/3. The branch should be feature/7 according to the issue description. Keep the branch as is.

2023-09-25 19:30 UTC, igorTT commented on form.js
> +const showResponse = async(data) => {
It isn't an async function

2023-09-25 19:30 UTC, igorTT commented on form.js
> +        if (response.ok) {
Useless check. You have an error catch

2023-09-27 18:14 UTC, igorTT approved these changes

2023-09-27 18:14 UTC, merged